//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iproby.Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class announ
    {
        public announ()
        {
            this.customer_announ = new HashSet<customer_announ>();
            this.reviews = new HashSet<review>();
            this.likes = new HashSet<like>();
            this.visits = new HashSet<visit>();
            this.announ_target = new HashSet<announ_target>();
        }
    
        public int id { get; set; }
        public Nullable<int> type_id { get; set; }
        public string description { get; set; }
        public string about { get; set; }
        public string price { get; set; }
        public string subjects { get; set; }
        public string header { get; set; }
    
        public virtual announ_type announ_type { get; set; }
        public virtual ICollection<customer_announ> customer_announ { get; set; }
        public virtual ICollection<review> reviews { get; set; }
        public virtual ICollection<like> likes { get; set; }
        public virtual ICollection<visit> visits { get; set; }
        public virtual ICollection<announ_target> announ_target { get; set; }
    }
}
