//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iproby.Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class announ_target
    {
        public int id { get; set; }
        public int announ_id { get; set; }
        public string target_type { get; set; }
        public string description { get; set; }
    
        public virtual announ announ { get; set; }
    }
}
