//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iproby.Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class announ_type
    {
        public announ_type()
        {
            this.announs = new HashSet<announ>();
        }
    
        public int id { get; set; }
        public string type { get; set; }
        public string description { get; set; }
        public string parent_type { get; set; }
        public string seo_header { get; set; }
    
        public virtual ICollection<announ> announs { get; set; }
    }
}
