//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iproby.Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public contact()
        {
            this.customers = new HashSet<customer>();
        }
    
        public int contact_id { get; set; }
        public string email { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public string skype { get; set; }
        public string mobile { get; set; }
        public string address { get; set; }
        public string facebook { get; set; }
        public string vkontakte { get; set; }
        public string icq { get; set; }
        public string site { get; set; }
        public string avatar { get; set; }
        public string avatar_cropped { get; set; }
    
        public virtual ICollection<customer> customers { get; set; }
    }
}
