

//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iproby.Data_Model
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class iproby94_cust_dbEntities : DbContext
{
    public iproby94_cust_dbEntities()
        : base("name=iproby94_cust_dbEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<speciality> specialities { get; set; }

    public DbSet<sysdiagram> sysdiagrams { get; set; }

    public DbSet<contact> contacts { get; set; }

    public DbSet<customer> customers { get; set; }

    public DbSet<status> status { get; set; }

    public DbSet<education> educations { get; set; }

}

}

