
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iproby.Data_Model
{

using System;
    using System.Collections.Generic;
    
public partial class customer
{

    public int customer_id { get; set; }

    public string login { get; set; }

    public string password { get; set; }

    public int contact_id { get; set; }

    public int status_id { get; set; }

    public System.DateTime date_from { get; set; }

    public System.DateTime date_to { get; set; }

    public int active { get; set; }



    public virtual contact contact { get; set; }

    public virtual status status { get; set; }

}

}
