//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iproby.Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.customer_announ = new HashSet<customer_announ>();
            this.messages = new HashSet<message>();
            this.reviews = new HashSet<review>();
            this.requests = new HashSet<request>();
            this.options = new HashSet<option>();
        }
    
        public int customer_id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int contact_id { get; set; }
        public int status_id { get; set; }
        public System.DateTime date_from { get; set; }
        public System.DateTime date_to { get; set; }
        public int active { get; set; }
        public Nullable<int> confirmed_flag { get; set; }
    
        public virtual contact contact { get; set; }
        public virtual status status { get; set; }
        public virtual ICollection<customer_announ> customer_announ { get; set; }
        public virtual ICollection<message> messages { get; set; }
        public virtual ICollection<review> reviews { get; set; }
        public virtual ICollection<request> requests { get; set; }
        public virtual ICollection<option> options { get; set; }
    }
}
