//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iproby.Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class option
    {
        public int id { get; set; }
        public int customer_id { get; set; }
        public Nullable<int> send_email_from_clients_flag { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
