//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iproby.Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class option
    {
        public int id { get; set; }
        public int customer_id { get; set; }
        public Nullable<int> send_email_from_clients_flag { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
