//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iproby.Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public int id { get; set; }
        public int from_customer_id { get; set; }
        public string request_rext { get; set; }
        public Nullable<System.DateTime> date_from { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
