//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iproby.Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class review
    {
        public int id { get; set; }
        public int announ_id { get; set; }
        public int customer_id { get; set; }
        public int reviewer_id { get; set; }
        public string header { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> date_from { get; set; }
    
        public virtual announ announ { get; set; }
        public virtual customer customer { get; set; }
    }
}
