//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iproby.Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class speciality
    {
        public int speciality_id { get; set; }
        public string target_table_name { get; set; }
        public string type { get; set; }
        public string desciption { get; set; }
    }
}
