//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iproby.Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class status
    {
        public status()
        {
            this.customers = new HashSet<customer>();
        }
    
        public int status_id { get; set; }
        public int status_flag { get; set; }
        public string status_description { get; set; }
    
        public virtual ICollection<customer> customers { get; set; }
    }
}
